apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- namespace.yaml
- prometheus-config.yaml
- prometheus-deployment.yaml
- grafana-deployment.yaml
- grafana-datasources.yaml
- grafana-dashboards.yaml

commonLabels:
  app: monitoring
  purpose: observability
  environment: development
