# Production environment patches for backup resources
apiVersion: v1
kind: VolumeSnapshotClass
metadata:
  name: todo-production-snapshot-class
  labels:
    environment: production
spec:
  deletionPolicy: Retain  # Keep snapshots longer in production
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-production-backup-pvc
  labels:
    environment: production
  annotations:
    backup.kubernetes.io/retention: "90d"  # Longer retention in production
    backup.kubernetes.io/encryption: "true"  # Enable encryption
spec:
  resources:
    requests:
      storage: 50Gi  # Larger storage for production
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-production-database-backup
  labels:
    environment: production
spec:
  schedule: "0 */6 * * *"  # Every 6 hours in production
  successfulJobsHistoryLimit: 14  # Keep more history
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: database-backup
            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
              requests:
                cpu: "500m"
                memory: "512Mi"
