# Spring Boot Application Configuration
spring:
  application:
    name: todo-backend
  profiles:
    active: development
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tododb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    # Connection pool settings
    hikari:
      auto-commit: true
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # Disable transaction management
        connection:
          provider_disables_autocommit: false
        # Disable second-level cache
        cache:
          use_second_level_cache: false
          use_query_cache: false
  
  # Redis Configuration (temporarily disabled)
  # redis:
  #   host: ${SPRING_REDIS_HOST:${REDIS_HOST:localhost}}
  #   port: ${SPRING_REDIS_PORT:${REDIS_PORT:6379}}
  #   password: ${SPRING_REDIS_PASSWORD:${REDIS_PASSWORD:}}
  #   timeout: 2000ms
  #   lettuce:
  #     pool:
  #       max-active: 8
  #       max-idle: 8
  #       min-idle: 0
  #       max-wait: -1ms

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        todo.creation.duration: true
        todo.completion.duration: true

# Logging Configuration
logging:
  level:
    com.todoapp: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/todo-app.log

# Cache Configuration
  cache:
    type: simple

# Profiles
---
spring:
  config:
    activate:
      on-profile: development
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
logging:
  level:
    com.todoapp: DEBUG

---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
logging:
  level:
    com.todoapp: INFO
