global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API - Spring Boot Actuator
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL (if we add postgres_exporter later)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres:5432']

  # Redis (if we add redis_exporter later)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis:6379']
