apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: todo-backend-hpa
spec:
  # Development: Conservative scaling
  minReplicas: 1
  maxReplicas: 3
  
  # Development: Less aggressive scaling
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # 10 minutes (more stable)
      policies:
      - type: Percent
        value: 25
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 120   # 2 minutes (more stable)
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      - type: Pods
        value: 1
        periodSeconds: 30
  
  # Development: Higher thresholds (less sensitive)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # Scale up at 80% CPU
  
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85  # Scale up at 85% Memory
