apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ../../namespaces

namespace: app

patches:
- target:
    kind: Deployment
    name: app
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: add
      path: /metadata/labels/environment
      value: development

labels:
- pairs:
    environment: development
