apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: todo-backend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: add
      path: /metadata/labels/environment
      value: development

- target:
    kind: Deployment
    name: todo-frontend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: add
      path: /metadata/labels/environment
      value: development

- target:
    kind: Deployment
    name: todo-nginx
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: add
      path: /metadata/labels/environment
      value: development

- target:
    kind: Deployment
    name: todo-postgres
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: add
      path: /metadata/labels/environment
      value: development

commonLabels:
  environment: development

namespace: todo-app
