apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-webhook-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-webhook-config
    app.kubernetes.io/part-of: argocd
data:
  webhook-config.yaml: |
    # ArgoCD Webhook Configuration
    # This allows external systems to trigger ArgoCD sync
    
    # GitHub webhook configuration
    github:
      enabled: true
      secret: "github-webhook-secret"
      events:
        - push
        - workflow_run
      repositories:
        - owner: "samidh93"
          name: "k8s_cluster_project"
          branch: "main"
          path: "helm/todo-app"
    
    # Generic webhook configuration
    generic:
      enabled: true
      secret: "generic-webhook-secret"
      applications:
        - name: "todo-app"
          namespace: "argocd"
          syncPolicy:
            prune: true
            selfHeal: true
            allowEmpty: false
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-webhook-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-webhook-secrets
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  github-webhook-secret: Z2l0aHViLXdlYmhvb2stc2VjcmV0  # base64 encoded "github-webhook-secret"
  generic-webhook-secret: Z2VuZXJpYy13ZWJob29rLXNlY3JldA==  # base64 encoded "generic-webhook-secret"
