# Blue Deployment (Current Active)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-blue
  namespace: todo-app
  labels:
    app: todo-backend
    version: blue
    environment: development
    purpose: blue-green-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
      version: blue
  template:
    metadata:
      labels:
        app: todo-backend
        version: blue
        environment: development
        purpose: blue-green-deployment
    spec:
      serviceAccountName: todo-backend-sa
      containers:
      - name: todo-backend
        image: ghcr.io/samidh93/todo-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "development"
        - name: DB_HOST
          value: "todo-postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "tododb"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: db.username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: db.password
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
# Green Deployment (Standby)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-green
  namespace: todo-app
  labels:
    app: todo-backend
    version: green
    environment: development
    purpose: blue-green-deployment
spec:
  replicas: 0  # Start with 0 replicas
  selector:
    matchLabels:
      app: todo-backend
      version: green
  template:
    metadata:
      labels:
        app: todo-backend
        version: green
        environment: development
        purpose: blue-green-deployment
    spec:
      serviceAccountName: todo-backend-sa
      containers:
      - name: todo-backend
        image: ghcr.io/samidh93/todo-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "development"
        - name: DB_HOST
          value: "todo-postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "tododb"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: db.username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: db.password
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
# Blue Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-blue
  namespace: todo-app
  labels:
    app: todo-frontend
    version: blue
    environment: development
    purpose: blue-green-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-frontend
      version: blue
  template:
    metadata:
      labels:
        app: todo-frontend
        version: blue
        environment: development
        purpose: blue-green-deployment
    spec:
      serviceAccountName: todo-frontend-sa
      containers:
      - name: todo-frontend
        image: ghcr.io/samidh93/todo-frontend:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
---
# Green Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-green
  namespace: todo-app
  labels:
    app: todo-frontend
    version: blue
    environment: development
    purpose: blue-green-deployment
spec:
  replicas: 0  # Start with 0 replicas
  selector:
    matchLabels:
      app: todo-frontend
      version: green
  template:
    metadata:
      labels:
        app: todo-frontend
        version: green
        environment: development
        purpose: blue-green-deployment
    spec:
      serviceAccountName: todo-frontend-sa
      containers:
      - name: todo-frontend
        image: ghcr.io/samidh93/todo-frontend:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
