apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-init-scripts
  namespace: todo-app
  labels:
    app: todo-app
data:
  init.sql: |
    -- Create database if not exists
    CREATE DATABASE IF NOT EXISTS tododb;
    
    -- Create tables
    CREATE TABLE IF NOT EXISTS todos (
        id SERIAL PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        description TEXT,
        completed BOOLEAN DEFAULT FALSE,
        priority VARCHAR(20) DEFAULT 'MEDIUM',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    -- Create indexes
    CREATE INDEX IF NOT EXISTS idx_todos_completed ON todos(completed);
    CREATE INDEX IF NOT EXISTS idx_todos_priority ON todos(priority);
    CREATE INDEX IF NOT EXISTS idx_todos_created_at ON todos(created_at);
    
    -- Insert sample data
    INSERT INTO todos (title, description, priority) VALUES
        ('Complete Kubernetes Setup', 'Set up local minikube cluster and deploy Todo app', 'HIGH'),
        ('Test CI/CD Pipeline', 'Verify GitHub Actions workflow works end-to-end', 'HIGH'),
        ('Create Monitoring Dashboards', 'Set up Grafana dashboards for Todo app metrics', 'MEDIUM'),
        ('Document Deployment Process', 'Write deployment guide for team members', 'LOW')
    ON CONFLICT DO NOTHING;
