apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- storage-class.yaml
- persistent-volume-claim.yaml
- configmap.yaml
- secret.yaml

labels:
- pairs:
    app: app
    version: v1
