apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-postgres-pvc
  namespace: todo-app
  labels:
    app: todo-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
