apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: todo-app
  labels:
    app: todo-app
type: Opaque
data:
  # Database credentials (base64 encoded)
  # To generate: echo -n "postgres" | base64
  db.username: cG9zdGdyZXM=
  # To generate: echo -n "todoapp_password" | base64
  db.password: dG9kb2FwcF9wYXNzd29yZA==
  
  # Application secrets
  app.secret.key: dG9kb2FwcC1zZWNyZXQta2V5LWZvci1kZXZlbG9wbWVudA==
  
  # Redis password (if using Redis)
  redis.password: cmVkaXNfcGFzc3dvcmQ=
